/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as OnboardIndexRouteImport } from './routes/onboard.index'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as LayoutTermsRouteImport } from './routes/_layout.terms'
import { Route as LayoutPrivacyRouteImport } from './routes/_layout.privacy'
import { Route as LayoutAppIndexRouteImport } from './routes/_layout.app.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as LayoutAppSocialsRouteImport } from './routes/_layout.app.socials'
import { Route as LayoutAppProvidersRouteImport } from './routes/_layout.app.providers'
import { Route as LayoutAppMcpRouteImport } from './routes/_layout.app.mcp'
import { Route as ApiIntegrationsNotionConnectRouteImport } from './routes/api/integrations/notion/connect'
import { Route as ApiIntegrationsNotionCallbackRouteImport } from './routes/api/integrations/notion/callback'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardIndexRoute = OnboardIndexRouteImport.update({
  id: '/onboard/',
  path: '/onboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutTermsRoute = LayoutTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPrivacyRoute = LayoutPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAppIndexRoute = LayoutAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAppSocialsRoute = LayoutAppSocialsRouteImport.update({
  id: '/app/socials',
  path: '/app/socials',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAppProvidersRoute = LayoutAppProvidersRouteImport.update({
  id: '/app/providers',
  path: '/app/providers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAppMcpRoute = LayoutAppMcpRouteImport.update({
  id: '/app/mcp',
  path: '/app/mcp',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiIntegrationsNotionConnectRoute =
  ApiIntegrationsNotionConnectRouteImport.update({
    id: '/api/integrations/notion/connect',
    path: '/api/integrations/notion/connect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsNotionCallbackRoute =
  ApiIntegrationsNotionCallbackRouteImport.update({
    id: '/api/integrations/notion/callback',
    path: '/api/integrations/notion/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/privacy': typeof LayoutPrivacyRoute
  '/terms': typeof LayoutTermsRoute
  '/api/chat': typeof ApiChatRoute
  '/onboard/': typeof OnboardIndexRoute
  '/app/mcp': typeof LayoutAppMcpRoute
  '/app/providers': typeof LayoutAppProvidersRoute
  '/app/socials': typeof LayoutAppSocialsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/': typeof LayoutAppIndexRoute
  '/api/integrations/notion/callback': typeof ApiIntegrationsNotionCallbackRoute
  '/api/integrations/notion/connect': typeof ApiIntegrationsNotionConnectRoute
}
export interface FileRoutesByTo {
  '/privacy': typeof LayoutPrivacyRoute
  '/terms': typeof LayoutTermsRoute
  '/api/chat': typeof ApiChatRoute
  '/': typeof LayoutIndexRoute
  '/onboard': typeof OnboardIndexRoute
  '/app/mcp': typeof LayoutAppMcpRoute
  '/app/providers': typeof LayoutAppProvidersRoute
  '/app/socials': typeof LayoutAppSocialsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app': typeof LayoutAppIndexRoute
  '/api/integrations/notion/callback': typeof ApiIntegrationsNotionCallbackRoute
  '/api/integrations/notion/connect': typeof ApiIntegrationsNotionConnectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/privacy': typeof LayoutPrivacyRoute
  '/_layout/terms': typeof LayoutTermsRoute
  '/api/chat': typeof ApiChatRoute
  '/_layout/': typeof LayoutIndexRoute
  '/onboard/': typeof OnboardIndexRoute
  '/_layout/app/mcp': typeof LayoutAppMcpRoute
  '/_layout/app/providers': typeof LayoutAppProvidersRoute
  '/_layout/app/socials': typeof LayoutAppSocialsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_layout/app/': typeof LayoutAppIndexRoute
  '/api/integrations/notion/callback': typeof ApiIntegrationsNotionCallbackRoute
  '/api/integrations/notion/connect': typeof ApiIntegrationsNotionConnectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/api/chat'
    | '/onboard/'
    | '/app/mcp'
    | '/app/providers'
    | '/app/socials'
    | '/api/auth/$'
    | '/app/'
    | '/api/integrations/notion/callback'
    | '/api/integrations/notion/connect'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/privacy'
    | '/terms'
    | '/api/chat'
    | '/'
    | '/onboard'
    | '/app/mcp'
    | '/app/providers'
    | '/app/socials'
    | '/api/auth/$'
    | '/app'
    | '/api/integrations/notion/callback'
    | '/api/integrations/notion/connect'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/privacy'
    | '/_layout/terms'
    | '/api/chat'
    | '/_layout/'
    | '/onboard/'
    | '/_layout/app/mcp'
    | '/_layout/app/providers'
    | '/_layout/app/socials'
    | '/api/auth/$'
    | '/_layout/app/'
    | '/api/integrations/notion/callback'
    | '/api/integrations/notion/connect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  OnboardIndexRoute: typeof OnboardIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiIntegrationsNotionCallbackRoute: typeof ApiIntegrationsNotionCallbackRoute
  ApiIntegrationsNotionConnectRoute: typeof ApiIntegrationsNotionConnectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard/': {
      id: '/onboard/'
      path: '/onboard'
      fullPath: '/onboard/'
      preLoaderRoute: typeof OnboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/terms': {
      id: '/_layout/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof LayoutTermsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/privacy': {
      id: '/_layout/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof LayoutPrivacyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/app/': {
      id: '/_layout/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof LayoutAppIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/app/socials': {
      id: '/_layout/app/socials'
      path: '/app/socials'
      fullPath: '/app/socials'
      preLoaderRoute: typeof LayoutAppSocialsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/app/providers': {
      id: '/_layout/app/providers'
      path: '/app/providers'
      fullPath: '/app/providers'
      preLoaderRoute: typeof LayoutAppProvidersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/app/mcp': {
      id: '/_layout/app/mcp'
      path: '/app/mcp'
      fullPath: '/app/mcp'
      preLoaderRoute: typeof LayoutAppMcpRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/integrations/notion/connect': {
      id: '/api/integrations/notion/connect'
      path: '/api/integrations/notion/connect'
      fullPath: '/api/integrations/notion/connect'
      preLoaderRoute: typeof ApiIntegrationsNotionConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/notion/callback': {
      id: '/api/integrations/notion/callback'
      path: '/api/integrations/notion/callback'
      fullPath: '/api/integrations/notion/callback'
      preLoaderRoute: typeof ApiIntegrationsNotionCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LayoutRouteChildren {
  LayoutPrivacyRoute: typeof LayoutPrivacyRoute
  LayoutTermsRoute: typeof LayoutTermsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAppMcpRoute: typeof LayoutAppMcpRoute
  LayoutAppProvidersRoute: typeof LayoutAppProvidersRoute
  LayoutAppSocialsRoute: typeof LayoutAppSocialsRoute
  LayoutAppIndexRoute: typeof LayoutAppIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutPrivacyRoute: LayoutPrivacyRoute,
  LayoutTermsRoute: LayoutTermsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAppMcpRoute: LayoutAppMcpRoute,
  LayoutAppProvidersRoute: LayoutAppProvidersRoute,
  LayoutAppSocialsRoute: LayoutAppSocialsRoute,
  LayoutAppIndexRoute: LayoutAppIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  OnboardIndexRoute: OnboardIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiIntegrationsNotionCallbackRoute: ApiIntegrationsNotionCallbackRoute,
  ApiIntegrationsNotionConnectRoute: ApiIntegrationsNotionConnectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
